### ISSUE TITLE
ssl.test fails with OpenSSL 3.0

### ISSUE THREAD

**Issue by nmeum** [msteveb/jimtcl#207] opened 2021-09-29 06:46 UTC
Hi,

While working on the [Alpine Linux](https://alpinelinux.org) package for jimtcl recently. I noticed that jimtcl-0.80 builds fine on x86_64 with OpenSSL 3.0 but the ssl.test fails with `unexpected EOF`:

```
make[1]: *** [Makefile:7: test] Broken pipe
make[1]: Leaving directory '/home/soeren/src/aports/community/jimtcl/src/jimtcl-0.80/tests'
ssl.test:24: Error: stream: error:0A000126:SSL routines::unexpected eof while reading
at file "ssl.test", line 24
make: *** [Makefile:95: check] Error 2
```

I haven't investigated the test failure further but would be nice to get this fixed.

Full build log: [alpine-linux-edge-x86_64-jimctl-0.80.txt](https://github.com/msteveb/jimtcl/files/7249462/alpine-linux-edge-x86_64-jimctl-0.80.txt)

**Comment by msteveb** [comment] 2021-10-06 20:52
Interesting. So it looks like SSL_pending() is returning a number of bytes available to read that then don't exist when we read them. Will need some investigation which will have to wait until I can reproduce this.

**Comment by ncopa** [comment] 2022-04-04 14:21
Gave it another try today and issue still exists

```
LD_LIBRARY_PATH="/home/ncopa/aports/community/jimtcl/src/jimtcl-0.81:" make -C tests jimsh="/home/ncopa/aports/community/jimtcl/src/jimtcl-0.81/jimsh"
make[1]: Entering directory '/home/ncopa/aports/community/jimtcl/src/jimtcl-0.81/tests'
        aio.test: Total    29   Passed    29  Skipped     0  Failed     0
      alias.test: Total    34   Passed    34  Skipped     0  Failed     0
      apply.test: Total    25   Passed    21  Skipped     4  Failed     0
    applyns.test: Total    15   Passed    11  Skipped     4  Failed     0
      array.test: Total    28   Passed    28  Skipped     0  Failed     0
     binary.test: Total   591   Passed   491  Skipped   100  Failed     0
      clock.test: Total    19   Passed    19  Skipped     0  Failed     0
     concat.test: Total    16   Passed    16  Skipped     0  Failed     0
   coverage.test: Total    34   Passed    28  Skipped     6  Failed     0
      debug.test:   --- skipped (command debug)
      defer.test: Total    15   Passed    15  Skipped     0  Failed     0
       dict.test: Total    78   Passed    78  Skipped     0  Failed     0
      dict2.test: Total   211   Passed   206  Skipped     5  Failed     0
      error.test: Total     3   Passed     3  Skipped     0  Failed     0
      event.test: Total    22   Passed    21  Skipped     1  Failed     0
       exec.test: Total    78   Passed    78  Skipped     0  Failed     0
      exec2.test:   --- skipped  (fails on Alpine builders, but works CI, dunno why)
     exists.test: Total    18   Passed    18  Skipped     0  Failed     0
     expand.test: Total     4   Passed     4  Skipped     0  Failed     0
  expr-base.test: Total    27   Passed    27  Skipped     0  Failed     0
   expr-new.test: Total   208   Passed   208  Skipped     0  Failed     0
   expr-old.test: Total   349   Passed   345  Skipped     4  Failed     0
   expr-pow.test: Total   147   Passed   136  Skipped    11  Failed     0
       expr.test: Total    29   Passed    29  Skipped     0  Failed     0
  exprsugar.test: Total    13   Passed    13  Skipped     0  Failed     0
       file.test: Total   108   Passed   108  Skipped     0  Failed     0
   filecopy.test: Total    17   Passed    17  Skipped     0  Failed     0
    filedir.test: Total    11   Passed    11  Skipped     0  Failed     0
        for.test: Total     9   Passed     9  Skipped     0  Failed     0
     format.test: Total   244   Passed   244  Skipped     0  Failed     0
       glob.test: Total    12   Passed    12  Skipped     0  Failed     0
      glob2.test: Total    41   Passed    32  Skipped     9  Failed     0
    history.test: Total     7   Passed     7  Skipped     0  Failed     0
  infoframe.test: Total     4   Passed     4  Skipped     0  Failed     0
interactive.test: Total     7   Passed     7  Skipped     0  Failed     0
    intexpr.test: Total    27   Passed    27  Skipped     0  Failed     0
        jim.test: Total   635   Passed   635  Skipped     0  Failed     0
  jiminterp.test: Total     4   Passed     4  Skipped     0  Failed     0
      jimsh.test: Total    11   Passed    11  Skipped     0  Failed     0
       json.test: Total    33   Passed    33  Skipped     0  Failed     0
    linsert.test: Total    28   Passed    27  Skipped     1  Failed     0
       list.test: Total    73   Passed    73  Skipped     0  Failed     0
       load.test:   --- skipped  (no working build-jim-ext)
       lock.test: Total     6   Passed     6  Skipped     0  Failed     0
       loop.test: Total    18   Passed    18  Skipped     0  Failed     0
     lrange.test: Total    22   Passed    20  Skipped     2  Failed     0
   lreplace.test: Total    59   Passed    59  Skipped     0  Failed     0
    lsearch.test: Total    81   Passed    81  Skipped     0  Failed     0
      lsort.test: Total    47   Passed    47  Skipped     0  Failed     0
   lsortcmd.test: Total     3   Passed     3  Skipped     0  Failed     0
       misc.test: Total   108   Passed   108  Skipped     0  Failed     0
  namespace.test: Total    79   Passed    79  Skipped     0  Failed     0
       pack.test: Total    25   Passed    25  Skipped     0  Failed     0
    package.test: Total     3   Passed     3  Skipped     0  Failed     0
      parse.test: Total    69   Passed    69  Skipped     0  Failed     0
       perf.test:   --- skipped (constraint manual)
        pid.test: Total     5   Passed     5  Skipped     0  Failed     0
      posix.test: Total     6   Passed     6  Skipped     0  Failed     0
     prefix.test: Total    36   Passed    36  Skipped     0  Failed     0
   proc-new.test: Total    35   Passed    35  Skipped     0  Failed     0
       proc.test: Total    62   Passed    62  Skipped     0  Failed     0
    procref.test: Total     6   Passed     6  Skipped     0  Failed     0
        ref.test: Total     1   Passed     1  Skipped     0  Failed     0
   regcount.test: Total    96   Passed    96  Skipped     0  Failed     0
     regexp.test: Total   161   Passed   161  Skipped     0  Failed     0
    regexp2.test: Total   168   Passed   167  Skipped     1  Failed     0
     regmin.test: Total    12   Passed    12  Skipped     0  Failed     0
     rename.test: Total    10   Passed    10  Skipped     0  Failed     0
     return.test: Total    10   Passed    10  Skipped     0  Failed     0
       scan.test: Total   164   Passed   164  Skipped     0  Failed     0
     signal.test: Total    32   Passed    32  Skipped     0  Failed     0
     socket.test:   --- skipped  (fails on Alpine builders, but works CI, dunno why)
/home/ncopa/aports/community/jimtcl/src/jimtcl-0.81/tests/ssl.test:24: Error: stream: error:0A000126:SSL routines::unexpected eof while reading
at file "/home/ncopa/aports/community/jimtcl/src/jimtcl-0.81/tests/ssl.test", line 24
ssl-2.1 ERR https to google.com, gets
/home/ncopa/aports/community/jimtcl/src/jimtcl-0.81/tests/ssl.test:64:Error test failure
Expected: rc={ok return} result={HTTP/1.0 200 OK*</html>}
Got     : rc=error result={stream: error:0A000126:SSL routines::unexpected eof while reading}

ssl-2.2 ERR https to google.com, read with cert verify
/home/ncopa/aports/community/jimtcl/src/jimtcl-0.81/tests/ssl.test:78:Error test failure
Expected: rc={ok return} result={HTTP/1.0 200 OK*</html>}
Got     : rc=error result={stream: error:0A000126:SSL routines::unexpected eof while reading}

        ssl.test: Total     5   Passed     3  Skipped     0  Failed     2
------------------------------------------------------------
FAILED: 2
	/home/ncopa/aports/community/jimtcl/src/jimtcl-0.81/tests/ssl.test:64	ssl-2.1
	/home/ncopa/aports/community/jimtcl/src/jimtcl-0.81/tests/ssl.test:78	ssl-2.2
------------------------------------------------------------
 stacktrace.test: Total    45   Passed    45  Skipped     0  Failed     0
     string.test: Total   321   Passed   315  Skipped     6  Failed     0
stringmatch.test: Total    61   Passed    61  Skipped     0  Failed     0
      subst.test: Total    41   Passed    39  Skipped     2  Failed     0
   tailcall.test: Total    11   Passed    11  Skipped     0  Failed     0
      timer.test: Total    43   Passed    43  Skipped     0  Failed     0
       tree.test: Total    15   Passed    15  Skipped     0  Failed     0
        try.test: Total    10   Passed    10  Skipped     0  Failed     0
    uplevel.test: Total    20   Passed    20  Skipped     0  Failed     0
      upvar.test: Total    41   Passed    41  Skipped     0  Failed     0
       utf8.test: Total    42   Passed    42  Skipped     0  Failed     0
     utftcl.test: Total    88   Passed    86  Skipped     2  Failed     0
       util.test: Total   130   Passed   118  Skipped    12  Failed     0
      while.test: Total    16   Passed    16  Skipped     0  Failed     0
     xtrace.test: Total     4   Passed     4  Skipped     0  Failed     0
       zlib.test: Total    31   Passed    31  Skipped     0  Failed     0
=========================================================================
          Totals: Total  5528   Passed  5354  Skipped   170  Failed     2
make[1]: *** [Makefile:5: test] Error 1
make[1]: Leaving directory '/home/ncopa/aports/community/jimtcl/src/jimtcl-0.81/tests'
make: *** [Makefile:101: check] Error 2
>>> ERROR: jimtcl: check failed
```

**Comment by msteveb** [comment] 2022-04-04 21:41
What version of Alpine Linux is this? My 3.14 doesn't have openssl3

**Comment by msteveb** [comment] 2022-04-04 22:39
Never mind. I reproduced it with 3.15. I pushed a fix to branch openssl3-fix. Can you test it?

**Comment by ncopa** [comment] 2022-04-05 08:35
I can confirm that this solves it and makes the tests pass. Thank you!

**Closed** 2022-04-05 08:41 UTC
